### ISSUE TITLE
Mach mal was :D

### ISSUE THREAD

**Issue by lnjX** [JBBgameich/admintools#1]
Mach doch mal was wie wärs mit ner init.lua und README.txt

**Comment by jbruechert** [comment]
YO chill mal das hat ja zeit und kommt alles noch

**Comment by lnjX** [comment]
Yo ich chill schon vor meine Komputa-Gereäte

**Comment by jbruechert** [comment]
Trotz riesiger historischer Relevanz werde ich diesen Issue mal schließen :D
